# Generated by Django 4.0.2 on 2023-04-12 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('size', models.FloatField(verbose_name='size')),
                ('ext', models.CharField(blank=True, default='', max_length=50, verbose_name='extension')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('shared_link', models.CharField(blank=True, max_length=50)),
                ('encrypted', models.BooleanField(default=False, verbose_name='encrypted')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
